services:
  - type: web
    name: portfolio-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: PUSHOVER_USER
        sync: false
      - key: PUSHOVER_TOKEN
        sync: false

  - type: web
    name: portfolio-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend.prod
    envVars:
      - key: REACT_APP_API_URL
        value: https://personal-website-7s6r.onrender.com
